networks:
  gap.network:
    external: true

services:
#  https://hub.docker.com/_/adminer/
  adminer:
    container_name: gap.adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "8085:8080" # http://127.0.0.1:8085/
    networks:
      gap.network: