### Variables
@baseUrl = http://localhost:8080

### Check server availability
GET {{baseUrl}}/ping

### Список товаров
GET {{baseUrl}}/goods/list?limit=100&offset=0
Content-Type: application/json
Accept: application/json

{}

### Обновить товар
PATCH {{baseUrl}}/goods/update?id=2137910346&projectId=1
Content-Type: application/json
Accept: application/json

{
  "name": "updated name3464"
}

### Создать товар
POST {{baseUrl}}/goods/create?projectId=1
Content-Type: application/json
Accept: application/json

{
  "name": "new name"
}