#volumes:
#  gap.pgsql.data:

networks:
  gap.network:
    external: true

services:
  server:
    container_name: gap.server
    build:
      context: ../
      dockerfile: ./goods-and-projects.Dockerfile
    networks:
      gap.network:
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      pgsql:
        condition: service_healthy
      nats:
        condition: service_healthy
    command:
      - "--http-addr"
      - ":8080"
      - "--redis-url"
      - "redis://redis:6379"
      - "--pgsql-dsn"
      - "postgresql://postgres:postgres@pgsql:5432/gapdb?sslmode=disable"
      - "--nats-url"
      - "nats://nats:4222"

  event-listener:
    container_name: gap.event-listener
    build:
      context: ../
      dockerfile: ./goods-event-listener.Dockerfile
    networks:
      gap.network:
    depends_on:
      clickhouse:
        condition: service_healthy
      nats:
        condition: service_healthy
    command:
      - "--nats-url"
      - "nats://nats:4222"
      - "--clickhouse-dsn"
      - "clickhouse://clickhouse:clickhouse@clickhouse:8123"

# https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker/
  redis:
    container_name: gap.redis
    image: redis:8
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      gap.network:
        aliases:
          - redis

# https://github.com/docker-library/docs/blob/master/postgres/README.md
  pgsql:
    container_name: gap.pgsql
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gapdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgsql/init:/docker-entrypoint-initdb.d
    networks:
      gap.network:
        aliases:
          - pgsql
#    volumes:
#      - gap.pgsql.data:/var/lib/postgresql/data

# https://docs.nats.io/running-a-nats-service/nats_docker
  nats:
    container_name: gap.nats
    image: nats:2.9-alpine
    restart: unless-stopped
    ports:
      - "4222:4222"
      - "8222:8222" # http://127.0.0.1:8222/
    healthcheck:
      test: ["CMD-SHELL", "wget http://localhost:8222/healthz -q -S -O -"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      gap.network:
        aliases:
          - nats
    command:
      - "-m"
      - "8222"
      - "-p"
      - "4222"

# https://hub.docker.com/r/clickhouse/clickhouse-server/
  clickhouse:
    container_name: gap.clickhouse
    image: clickhouse/clickhouse-server:25.1
    restart: unless-stopped
    ports:
      - "8123:8123"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
        - ./clickhouse/init:/docker-entrypoint-initdb.d
    networks:
      gap.network:
        aliases:
          - clickhouse